### ISSUE TITLE
2747_c3 - Haoyu-ECE3.mp4

### ISSUE THREAD

**Issue by JustinLinKK** [macrobomaster/cv-yolov7#10]

**Comment by JustinLinKK** [comment]
https://drive.google.com/file/d/108B10_GiyH6dJ1EFgGOJOK6qt4AC8hVP/view?usp=share_link
This is the dataset annotated and zipped with pictures.

**Comment by Bill-Haoyu-Lin** [comment]
Need to fix big armor plate. We don't need big armor-plate so far

**Comment by Bill-Haoyu-Lin** [comment]
Done and merged
