### ISSUE TITLE
2747_c1.mp4 - Allen-ENGI

### ISSUE THREAD

**Issue by Allen-ENGI** [macrobomaster/cv-yolov7#11]

**Comment by Allen-ENGI** [comment]
This is the link to the zip file: https://drive.google.com/file/d/1Y8IMUFqT_QM1FDp7-45PkFDmJ4Vu1397/view?usp=sharing

**Comment by Bill-Haoyu-Lin** [comment]
Need to re-label. No big armor plate is needed for now. The labeling need to be more accurate

**Comment by Allen-ENGI** [comment]
Update version with correction: https://drive.google.com/file/d/1hM_rURHKk5DmL21H9o1NEw4yTUGwX2cE/view?usp=sharing

**Comment by Bill-Haoyu-Lin** [comment]
Need to add label inside

**Comment by Allen-ENGI** [comment]
update file with correct file type and labels: https://drive.google.com/file/d/1gPMyxaPO7tGHEl3rZAa1bNo-o71sYBDZ/view?usp=sharing

**Comment by Allen-ENGI** [comment]
update the labels: https://drive.google.com/file/d/1qafIxRJA_wSi9rttYqhn6c5y9TfbsZ4K/view?usp=sharing

**Comment by Allen-ENGI** [comment]
update the labels with the image: https://drive.google.com/file/d/1QJpM7aBdIGLb9WmfEM5tLXwfw5l7Sjv3/view?usp=sharing
