### ISSUE TITLE
2743_c3.mp4 -- Keryn

### ISSUE THREAD

**Issue by liangk10** [macrobomaster/cv-yolov7#16]

**Comment by liangk10** [comment]
https://drive.google.com/file/d/1WGopRYYhnUYkk2stJmAGi0h0zuwkIWDC/view?usp=share_link

**Comment by Bill-Haoyu-Lin** [comment]
Good labeling! I will close this issue

**Comment by Bill-Haoyu-Lin** [comment]
Need to re-upload labeling data

**Comment by Bill-Haoyu-Lin** [comment]
Great work! Good job
