### ISSUE TITLE
10 past frames for kalman filter prediction for better result

### ISSUE THREAD

**Issue by Bill-Haoyu-Lin** [macrobomaster/cv-yolov7#21]
10 past frame for kalman filter prediction for better result. 
We need to include time of fly for bullet in our consideration, current 1 iteration prediction is not far-sight enough for our use. We need to make prediction better in accuracy as well as time.

**Comment by Allen-ENGI** [comment]
Have tried another way to do the prediction, by collecting the locations of the past ten frames and predicting the next location. Passed some simple tests but not sure it will fully work though

**Comment by Bill-Haoyu-Lin** [comment]
Good prediction result, need to make it converge faster. For both Kalman filter and new prediction result. 
![image](https://user-images.githubusercontent.com/56321690/222604706-adbfed53-c8f8-42a9-bbf8-521c8549cb6e.png)

**Comment by Allen-ENGI** [comment]
After testing, using 10 past frames is not as efficient and accurate as using the Kalman Filter algorithm. We shall prefer to use the Kalman Filter for further development.
