### ISSUE TITLE
Deploy object detection to TX2 Board 

### ISSUE THREAD

**Issue by Bill-Haoyu-Lin** [macrobomaster/cv-yolov7#23]
Deploy our python algorithm for object detection to TX2 board.

**Comment by JustinLinKK** [comment]
A sample .pt file is needed for the future development. We have the code and the deployment and test need the model file. Also the camera is needed for the test.

**Comment by Bill-Haoyu-Lin** [comment]
We have 3 camera in our hand. All global shutter, 120 fps and 640x640

> A sample .pt file is needed for the future development. We have the code and the deployment and test need the model file. Also the camera is needed for the test.

**Comment by Bill-Haoyu-Lin** [comment]
For now you can mp4 input instead of camera input. It also shows the fps for object detection. 

> A sample .pt file is needed for the future development. We have the code and the deployment and test need the model file. Also the camera is needed for the test.

**Comment by JustinLinKK** [comment]
> 

The model file is still needed, though. I can't do the file since my torch version and CUDA version are too high, and I'm still using the torch to do other development on GPT. Right now do we have any model usable?

**Comment by JustinLinKK** [comment]
The model is used for verifying the code could run in the TX2

**Comment by Bill-Haoyu-Lin** [comment]
> The model is used for verifying the code could run in the TX2

We have multiple usable models , this is one of the usable one trained by v3 https://drive.google.com/file/d/1Hi-snbU5REBrPB0tr1sGIy55vJTHEXBf/view?usp=share_link

**Comment by Bill-Haoyu-Lin** [comment]
> > 
> 
> The model file is still needed, though. I can't do the file since my torch version and CUDA version are too high, and I'm still using the torch to do other development on GPT. Right now do we have any model usable?

you may need to migrate it to support higher level of torch and cuda

**Comment by JustinLinKK** [comment]
https://user-images.githubusercontent.com/90200769/222779867-b4732a47-99ed-440b-9ef2-3899003e963f.mov

**Comment by Bill-Haoyu-Lin** [comment]
Finshed deploy on both jetson nano. Will move to improvement stage
